### ISSUE TITLE
tarefas gerais

### ISSUE THREAD

**Issue by gbmartins9** [k1sta/Projeto-Final-Prog-2#1]
- [ ] Menu para acessar funcionalidades
- [x] Estruturar dados que serão utilizados
- [x] Projetar escrita e leitura dos BD de produtos e movimentações
- [ ] Funções - Criação / Deleção de produtos no BD de produtos (estoque)
- [x] Função - Procura de entidade no BD de produtos
- [ ] Função - Modificação de atributos de entidades no BD de produtos (estoque)
- [ ] Funções - Adição / Remoção de movimentações no BD de histórico de movimentações de produtos
- [ ] Função - Procura de entidade no BD de histórico de movimentações de produtos
- [ ] Função - Modificação de atributos de movimentações no BD de histórico de movimentações de produtos
- [ ] Função - Compra de produtos
- [ ] Função - Caixa

**Comment by k1sta** [comment]
Fala pessoal!

Listei todos os arquivos no README.md e, no arquivo arqlib.h, as funções estão descritas com algumas observações.

**Comment by k1sta** [comment]
Problema encontrado:
- O arquivo está sendo aberto em cada função. Reimplementar para que o ponteiro do arquivo seja passado por referência (será aberto na main)

**Comment by k1sta** [comment]
closing topic due the creation of a new one :P

**Comment by k1sta** [comment]
closing topic due the creation of a new one :P
