### ISSUE TITLE
REQUISITOS OFICIAL

### ISSUE THREAD

**Issue by brunovschulz** [k1sta/Projeto-Final-Prog-2#2]

**Comment by brunovschulz** [comment]
Já prontos
- [x] pegar produto por arquivo
- [x] pegar produto por input
- [x] buscar produto do dat
- [x] modificar um produto

Em andamento (precisa ajeitar / revisar)
- [ ]  compra produto (de fornecedor)
- [ ]  remover produto (SOLUÇÃO COMPLICADA)
- [ ]  cadastrar produto (problema: ordenação
- [ ] modificar um produto

Não prontos
- [ ] Interação com o usuário - main
- [ ] caixa (retirar produtos do estoque diretamente da compra de um consumidor)

Requisitos inversos 

1.  Registro de compras (consumidor)

**Comment by k1sta** [comment]
- [ ] Adequação da função inputProdutosArquivo() para o formato .csv
- [ ] Um tapa no visual
